### PR TITLE
[torch-mlir earthmoving (1/N)] C/C++ code movement.

### PR DESCRIPTION
**Pull request by silvasean**
This creates the `external/torch-mlir` directory as an
LLVM_EXTERNAL_PROJECTS-compatible project (analogous to
`iree-dialects`) and completes movement/rename of all pure MLIR C/C++
compiler code into there. The next step will be to move all the Python
code / code that links/includes PyTorch C++ code (which currently lives
in `frontends/pytorch`) into a subdirectory here.

I call this "earthmoving" because it is mostly mechanical changes and
renames. As a quick summary (we can change this down the road easily)
- C++ `mlir::NPCOMP::Torch -> mlir::torch::Torch`
- CAPI `npcompTorchListTypeGet -> torchMlirTorchListTypeGet`
- preprocessor `#ifndef NPCOMP_ -> #ifndef TORCHMLIR_`
- CMake `NPCOMPFoo -> TorchMLIRFoo`

The goal of this is to create a standalone project creating a center of
mass for entry into the MLIR ecosystem from PyTorch, suitable in scope
for eventual inclusion/ownership in PyTorch. The idea is that
`external/torch-mlir` will some day be pulled out into its own
repository, and then npcomp will simply pull it in as a submodule.

Layering-wise, what lives in `torch-mlir` lowers code from PyTorch
(currently TorchScript, but TorchFX or pytorch/xla-style tracing are
possible extensions) down to what we have been calling the "Torch
backend contract" which is cleaned up IR (inlining, simplifcation,
conversion to value tensors, ...) entirely in the `torch` dialect. This
is the branching off point for further lowering, of which npcomp takes
one opinion (outside `torch-mlir` of course!), namely the
`TorchConversion` dialect/transforms which lower to IR suitable for IREE
and other linalg-on-tensors based lower-level compilers.

Summary of changes:
- move `{include,lib,test}/Dialect/Torch` into `torch-mlir`
- move relevant parts of CAPI into `torch-mlir`.
- leave a few things related to the `torch-mlir` Python build commented
  out, which should be resolved in a subsequent change.

### CODE REVIEW

**Comment by silvasean** [comment]
@powderluv @harsh-nod @dan-garvey @ramiro050 @gpetters94 FYI: first step of the earthmoving we discussed.

**Comment by stephenneuendorffer** [comment]
Would it be worthwhile to have a presentation at the MLIR design meeting about the plans here at some point, presuming you think that this will stabilize?

**Comment by stellaraccident** [comment]
> Would it be worthwhile to have a presentation at the MLIR design meeting about the plans here at some point, presuming you think that this will stabilize?

Yes, happy to do that or a more focused meeting if there is a specific audience that would be interested.

Basically, a lot of this stuff is at a point of completion/utility, and in discussing with the Nod folks, we wanted to make a go at collapsing all of the PyTorch MVP parts into one project which is clean/standalone and that we could pitch for inclusion into upstream PyTorch. The goal would be to make this a "pure" MLIR import and not backend specific, hopefully being the concentration point that multiples of us have been hoping for. No idea how that will go, but it seemed pretty clear (to us) that with everything jumbled together, it was really hard to tell the crisp story of "this is reasonable/minimal MLIR ecosystem interface code to add to PyTorch".

Stephen: you've got a stake in this and if you feel like you want to discuss it more before going forward with this patch, we should pause and have the discussion. As it stands now, this is mostly a long overdue code cleanup and doesn't seem controversial (and I'll review it as such), but speak up if you'd like to talk more.

**Review by stellaraccident — APPROVED** [review]
Looks like a much better code organization. Thanks.

**Comment by stephenneuendorffer** [comment]
No need to pause.. Please go ahead with the refactoring.  I'm mostly trying to figure out how/when to try to intersect this again, possibly together with the new pytorch_xla interface.

**Comment by silvasean** [comment]
Going to land this and temporarily disable the python wheels building CI job, as that issue will be resolved when I rework the Python stuff in the next step. (and the CI will need some retouching after the earthmoving anyway, e.g. to make sure it runs check-torch-mlir)

**Comment by silvasean** [comment]
I'm really sorry for any merge conflicts this causes for anyone!!!

**Pull request merged**
