### PR TITLE
Rework the python build to a static assembly of MLIR+NPCOMP

### PR DESCRIPTION
**Pull request by stellaraccident**
This is pre-work for the upcoming integrate of https://reviews.llvm.org/D106520

It is irreducibly complex because that will be a large breaking change to the build system, and it enforces stricter layering than npcomp was complying with. There are additional cleanups that can be done once this lands.

Changes:

* Reworks the refjit python API to go through a new C-API (the new python support enforces this and, unfortunately, it was layered wrong before) -- this is the biggest functional change.
* Removes libNPCOMP.so building.
* Does a fully static build.
* Eliminates the split llvm install/npcomp build: it is now unified and builds with a default CMake config.
* Updates docs.

Looking for a pre-review as I will need to land this with an integrate in a ~few days.

I still need to update the CI.

### CODE REVIEW

**Comment by amaleewilson** [comment]
I had the issue in #154 that I believe this PR is supposed to fix. 

Just tried a totally fresh build using the pybuildrefactor branch and got this: 

```$ ninja check-npcomp
[10/11] Running the npcomp regression tests
FAIL: NPCOMP_OPT :: Python/Backend/RefJIT/simple_invoke_numpy.py (57 of 104)
******************** TEST 'NPCOMP_OPT :: Python/Backend/RefJIT/simple_invoke_numpy.py' FAILED ********************
Script:
--
: 'RUN: at line 1';   /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/bin/python3.8 /Users/wils220/mlir-npcomp/test/Python/Backend/RefJIT/simple_invoke_numpy.py | /Users/wils220/mlir-npcomp/build/llvm/bin/FileCheck /Users/wils220/mlir-npcomp/test/Python/Backend/RefJIT/simple_invoke_numpy.py --dump-input=fail
--
Exit Code: 2

Command Output (stderr):
--
DEBUG: Skipped ufunc: numpy.divmod (<ufunc 'divmod'>)
DEBUG: Skipped ufunc: numpy.frexp (<ufunc 'frexp'>)
DEBUG: Skipped ufunc: numpy.modf (<ufunc 'modf'>)
DEBUG: Partial eval mapping: MappedPartialEvalHook(refs={ 
...
Testing Time: 17.54s
  Unsupported:  2
  Passed     : 90
  Failed     : 12
FAILED: test/CMakeFiles/check-npcomp-lit /Users/wils220/mlir-npcomp/build/test/CMakeFiles/check-npcomp-lit 
cd /Users/wils220/mlir-npcomp/build/test && /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/bin/python3.8 /Users/wils220/mlir-npcomp/build/llvm/bin/llvm-lit -sv /Users/wils220/mlir-npcomp/build/test
ninja: build stopped: subcommand failed.
```

**Comment by stellaraccident** [comment]
> I see you just pushed 10 minutes ago. Will try again.

You're on MacOS, right? There may be additional fixes required for that -- I'll need to fire up my Mac next and triage (would be nice to get the CI set up too). Stand by... I'm just working through quite the backlog of things here but should have it resolved in the next day or so.

**Comment by amaleewilson** [comment]
> You're on MacOS, right? 

That's right. Sounds good, though, thank you for dealing with this!

**Comment by stellaraccident** [comment]
> > You're on MacOS, right?
> 
> That's right. Sounds good, though, thank you for dealing with this!

Ok, got this repro'd on my Mac. Your second issue, when you tried to run manually, is because the instructions for how to set your PYTHONPATH have drifted a bit. In your build directory, there will be a python_packages/ dir that contains two sub directories. Both need to be on your PYTHONPATH. I'll need to update docs/scripts.

The bigger issue is that the JIT is crashing. I've got a stack trace and need to run it down. It's never gotten this far on MacOS before, so something latent, I'm sure.

**Pull request merged**
