### PR TITLE
Bump llvm-project to e31c77b

### PR DESCRIPTION
**Pull request by byronyi**
Per MLIR Python API updates in https://reviews.llvm.org/D98096

### CODE REVIEW

**Comment by mikeurbach** [comment]
> Looks like some sort of issue related to cl::opt options being registered more than once?

I know we've seen this issue in CIRCT before... trying to remember if there was a clear resolution. I'm also going to be doing a similar LLVM version bump on CIRCT, so if we run into it there I will certainly share any insights.

**Comment by byronyi** [comment]
Use regular LLVM build by `./build_tools/install_mlir.sh` with the "Build and Test npcomp (Assert)" workflow, I didn't re-produce the failure. Maybe because I am using `clang-11` instead of clang bundled with Ubuntu 20.04 (looks like clang-9)?

**Comment by byronyi** [comment]
Reproduced when using `clang-9` for building LLVM (with either clang-9/11 for NPCOMP).

**Comment by byronyi** [comment]
@silvasean CI hit the cache but I may need to change the build options for LLVM here. 

Wondering if there is a way to clear the cache manually.

**Comment by stellaraccident** [comment]
> @silvasean CI hit the cache but I may need to change the build options for LLVM here.
> 
> Wondering if there is a way to clear the cache manually.

Just getting online: you can add a nonce value to the hash input: https://github.com/llvm/mlir-npcomp/blob/b94a859e03b4f42be85e4a8901e384023facb7cf/.github/workflows/buildAndTest.yml#L26

If a change to that file is in your pr, it should take effect.

**Comment by byronyi** [comment]
My attempt to fix this seems not working on GitHub CI environment. 

It's beyond my knowledge to debug LLVM internals so I will leave to @mikeurbach for further investigation. I've tested https://github.com/llvm/mlir-npcomp/pull/182/commits/b40a7507a364040ac1779492ef32f6b508d88878 locally and it is working.

**Comment by byronyi** [comment]
Somehow `-DLLVM_LINK_LLVM_DYLIB=ON` ~~`-DLLVM_ENABLE_LLD=ON`~~ works. Not sure why.

**Comment by stellaraccident** [comment]
FYI, the cl opt thing is typically a symptom of an odr violation of some sort. I suspect that changing some of the link flags is sending it back under the surface but not actually fixing it. If it helps, though, fine with me.

We actually need to be using BUILD_SHARED_LIBS mode instead of libMLIR. I'm not sure the latter can be fixed without a fair amount of work upstream. I'm busy today but can try to do this surgery later in the week.

**Comment by mikeurbach** [comment]
> I will leave to @mikeurbach for further investigation

FYI I will be performing the same LLVM bump on CIRCT this afternoon (MDT). I'll let you know how it goes on our end.

**Comment by silvasean** [comment]
Thanks folks for rallying around this. I'm going to go ahead and land this. Will be very interested to hear @mikeurbach 's findings with the circt bump.

**Comment by mikeurbach** [comment]
Well, I landed the LLVM update on CIRCT: https://github.com/llvm/circt/commit/ed6c6421a4dfce8471cec67e7f9c787a2fa2ba01. This wasn't bumped to the same commit as NPComp; I just took the latest LLVM main as of yesterday morning.

I didn't run into the issue with the CL opt stuff in any of our integration test matrix combinations:
https://github.com/llvm/circt/blob/ed6c6421a4dfce8471cec67e7f9c787a2fa2ba01/.github/workflows/nightlyIntegrationTests.yml#L54-L62

I did run into some weird behavior with our tests, if they combined expected-* diagnostic checks with regular FileChecks, but I don't think that has come up here.

Sorry I wasn't able to dig up more insight... at least both projects are working with the latest LLVM, and the GitHub tests seem to at least be stable.

**Comment by silvasean** [comment]
Thanks Mike. I guess we'll need to keep an eye on this issue and wait for it to crop up at some later date.

**Pull request merged**
