### PR TITLE
Refactor RefineTypes to use the upstream ForwardDataFlowAnalysis engine

### PR DESCRIPTION
**Pull request by River707**
This removes the need for defining all of the custom propagation logic,
and also adds support for propagating value knowledge across branches,
through regions, and across calls.

### CODE REVIEW

**Comment by River707** [comment]
@silvasean This is the patch I have been playing around with. I didn't really change any of the existing terminology/class names. I also added an example of call graph propagation, though this pass is currently a FunctionPass so that case wouldn't matter now anyways.

**Comment by stellaraccident** [comment]
This is really nice - thanks, River!

**Review by Ayushsunny — APPROVED** [review]

**Comment by silvasean** [comment]
Thanks River! I'll take care of shepherding this into tree so you don't have to worry about any integration or other details.

**Comment by silvasean** [comment]
Merged it in https://github.com/llvm/mlir-npcomp/commit/4678a7fedd029555785919da3e12f945f2837d18

Thanks!

**Pull request closed without merging**
