### PR TITLE
RFC: 2021Q3 roadmap

### PR DESCRIPTION
**Pull request by silvasean**
This is an open discussion and review!

### CODE REVIEW

**Review by stellaraccident — APPROVED** [review]

**Comment by bhack** [comment]
I have just a question why Torchscript?

**Comment by silvasean** [comment]
See the description of the project:

```
- TorchScript compilation: The goal of this project is to build the frontend of
  a truly next-generation ahead-of-time machine learning compiler.
  - Why this project is cool: This system is designed from day 1 to support
    features such as dynamic shapes, control flow, mutable variables,
    program-internal state, and non-Tensor types (scalars, lists, dicts) in a
    principled fashion. These features are essential for empowering an
    industry-level shift in the set of machine learning programs that are
    feasible to deploy with minimal effort across many devices (when combined
    with a backend using the advanced compilation techniques being developed
    elsewhere in the MLIR ecosystem).
```

Does this answer your question?

**Comment by bhack** [comment]
Yes I've read this, I supposed that it was focused on Torchscript as an alternative to https://github.com/pytorch/xla

I didn't see the alternatives analyzed in the Readme,  but maybe there aren't.

**Comment by byronyi** [comment]
Circulating https://github.com/pytorch/xla/pull/3015#issuecomment-871002882 for current torch-xla recompilation pain points and how a TorchScript -> MHLO pass could help.

**Comment by silvasean** [comment]
> Yes I've read this, I supposed that it was focused on Torchscript as an alternative to https://github.com/pytorch/xla
> 
> I didn't see the alternatives analyzed in the Readme, but maybe there aren't.

Ah yes, there is a missing rationale document. The short answer is that pytorch/xla is currently a tracing-based system, which is is not a viable approach for ahead-of-time compilation of programs of the kind that I am interested in. Specifically, the tracing process is an inherently lossy process that requires keeping the original program around for re-tracing if the trace is invalidated. The programs I am interested in are programs with dynamic shapes, control flow, mutable variables, program-internal state, and non-Tensor types (scalars, lists, dicts).

**Comment by bhack** [comment]
Ok but what It Is missing Is that:
this programs could be expressed in Torchscript or in ... or in ..?
So in the end why Torchscript?

**Comment by stellaraccident** [comment]
TorchScript is a good representation for these kind of constrained python programs and is a nice superset of general torch IR. We're building a compiler, and there is a strong affinity towards program forms that are complete, spec'd and preserve the source representations. 

Anyone who wants to use XLA should: its distinct benefit is that it exists and has a good deal of mileage on it. We don't think it has a lot of design room on it to be more than it is, though. None of this needs to be either/or.

**Comment by bhack** [comment]
What I meant more explcitely is there a strong connection between the Torchscript selection and the need to have a new "path" to bring pytorch on TPU?

**Comment by stellaraccident** [comment]
We'll have to see where the work goes. I personally will be happy in the near term with better deployability to CPU/GPU including edge and datacenter sized devices.

**Comment by bhack** [comment]
If this is the goal at some point we will need to "standardize" Torchscript with a more indipendent entity.

**Comment by byronyi** [comment]
> If this is the goal at some point we will need to "standardize" Torchscript with a more independent entity.

An open initiative would be great, but it needs to be successful first. I actually have less concerns for openness in the PyTorch community than the TF one :P

**Comment by stellaraccident** [comment]
+1 - agreed. Let's connect the dots, show value and then have a community discussion on where to go

**Pull request merged**
